service: shopify-clone

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  versionFunctions: false
  environment:
    DB_USER: ${env:DB_USER}
    DB_HOST: ${env:DB_HOST}
    DB_PASS: ${env.DB_PASS}
    DB_NAME: ${env.DB_NAME}
    DB_PORT: ${env.DB_PORT}
    JWT_SECRET: ${env.JWT_SECRET}
    STRIPE_SK: ${env.STRIPE_SK}

functions:
  graphql:
    handler: src/main.graphql
    events:
      - http:
          path: graphql
          method: any
          cors: true